#!/bin/bash
MYIP=$(wget -qO- ipinfo.io/ip);
echo "Checking VPS"
CEKEXPIRED () {
    today=$(date -d +1day +%Y-%m-%d)
    Exp1=$(curl -sS https://raw.githubusercontent.com/Tarap-Kuhing/Profile/main/Profile/permission/ip | grep $MYIP | awk '{print $3}')
    if [[ $today < $Exp1 ]]; then
    echo -e "\e[32mSTATUS SCRIPT AKTIF...\e[0m"
    else
    echo -e "\e[31mSCRIPT ANDA EXPIRED!\e[0m";

    exit 0
fi
}
IZIN=$(curl -sS https://raw.githubusercontent.com/Tarap-Kuhing/Profile/main/Profile/permission/ip | awk '{print $4}' | grep $MYIP)
if [ $MYIP = $IZIN ]; then
echo -e "\e[32mPermission Accepted...\e[0m"
CEKEXPIRED
else
echo -e "\e[31mPermission Denied!\e[0m";

exit 0
fi
clear
dateFromServer=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
biji=`date +"%Y-%m-%d" -d "$dateFromServer"`
###########- COLOR CODE -##############
echo -e "\E[44;1;39m ⇱ [INFO] Downloading Update File⇲        \E[0m"
sleep 5
echo -e "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━•"
echo -e "\E[44;1;39m               ⇱ 5 ⇲                      \E[0m"
echo -e "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━•"
sleep 4
echo -e "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━•"
echo -e "\E[44;1;39m               ⇱ 4 ⇲                      \E[0m"
echo -e "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━•"
sleep 3
echo -e "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━•"
echo -e "\E[44;1;39m               ⇱ 3 ⇲                      \E[0m"
echo -e "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━•"
sleep 2
echo -e "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━•"
echo -e "\E[44;1;39m               ⇱ 2 ⇲                      \E[0m"
echo -e "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━•"
sleep 1
echo -e "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━•"
echo -e "\E[44;1;39m               ⇱ 1 ⇲                      \E[0m"
echo -e "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━•"
echo -e""
echo -e "\033[0;36m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[m"
echo -e "\E[44;1;39m              ⇱ UPDATE ⇲                      \E[0m"
echo -e "\E[44;1;39m              ⇱ DIMULAI ⇲                     \E[0m"
echo -e "\033[0;36m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[m"
clear
# hapus menu
rm -rf menu
rm -rf menu-ss
rm -rf menu-vmess
rm -rf menu-vless
rm -rf menu-trojan
rm -rf menu-bot
rm -rf menu-ssh
rm -rf menu-set
rm -rf menu-theme
rm -rf menu-backup
rm -rf menu-ip
rm -rf menu-tor
rm -rf menu-tcp
rm -rf autoboot
rm -rf menu-tcp
rm -rf rebootvps
rm -rf menu-dns
rm -rf info
rm -rf mspeed
rm -rf mbandwith
rm -rf restart
rm -rf menu-update
# download menu
cd /usr/bin
rm -rf menu
rm -rf menu-update

wget -q -O /usr/bin/menu "https://raw.githubusercontent.com/Tarap-Kuhing/tarong/main/tarong/MENU/menu.sh" && chmod +x /usr/bin/menu
wget -q -O /usr/bin/menu-ss "https://raw.githubusercontent.com/Tarap-Kuhing/tarong/main/tarong/MENU/menu-ss.sh" && chmod +x /usr/bin/menu-ss
wget -q -O /usr/bin/menu-vmess "https://raw.githubusercontent.com/Tarap-Kuhing/tarong/main/tarong/MENU/menu-vmess.sh" && chmod +x /usr/bin/menu-vmess
wget -q -O /usr/bin/menu-vless "https://raw.githubusercontent.com/Tarap-Kuhing/tarong/main/tarong/MENU/menu-vless.sh" && chmod +x /usr/bin/menu-vless
wget -q -O /usr/bin/menu-trojan "https://raw.githubusercontent.com/Tarap-Kuhing/tarong/main/tarong/MENU/menu-trojan.sh" && chmod +x /usr/bin/menu-trojan
wget -q -O /usr/bin/menu-bot "https://raw.githubusercontent.com/Tarap-Kuhing/tarong/main/tarong/MENU/menu-bot.sh" && chmod +x /usr/bin/menu-bot
wget -q -O /usr/bin/menu-ssh "https://raw.githubusercontent.com/Tarap-Kuhing/tarong/main/tarong/MENU/menu-ssh.sh" && chmod +x /usr/bin/menu-ssh
wget -q -O /usr/bin/menu-set "https://raw.githubusercontent.com/Tarap-Kuhing/tarong/main/tarong/MENU/menu-set.sh" && chmod +x /usr/bin/menu-set
wget -q -O /usr/bin/menu-theme "https://raw.githubusercontent.com/Tarap-Kuhing/tarong/main/tarong/MENU/menu-theme.sh" && chmod +x /usr/bin/menu-theme
wget -q -O /usr/bin/menu-backup "https://raw.githubusercontent.com/Tarap-Kuhing/tarong/main/tarong/MENU/menu-backup.sh" && chmod +x /usr/bin/menu-backup
wget -q -O /usr/bin/menu-ip "https://raw.githubusercontent.com/Tarap-Kuhing/tarong/main/tarong/MENU/menu-ip.sh" && chmod +x /usr/bin/menu-ip
wget -q -O /usr/bin/menu-tor "https://raw.githubusercontent.com/Tarap-Kuhing/tarong/main/tarong/MENU/menu-tor.sh" && chmod +x /usr/bin/menu-tor
wget -q -O /usr/bin/autoboot "https://raw.githubusercontent.com/Tarap-Kuhing/tarong/main/tarong/MENU/autoboot.sh" && chmod +x /usr/bin/autoboot
wget -q -O /usr/bin/menu-tcp "https://raw.githubusercontent.com/Tarap-Kuhing/tarong/main/tarong/MENU/menu-tcp.sh" && chmod +x /usr/bin/menu-tcp
wget -q -O /usr/bin/rebootvps "https://raw.githubusercontent.com/Tarap-Kuhing/tarong/main/tarong/MENU/rebootvps.sh" && chmod +x /usr/bin/rebootvps
wget -q -O /usr/bin/menu-dns "https://raw.githubusercontent.com/Tarap-Kuhing/tarong/main/tarong/MENU/menu-dns.sh" && chmod +x /usr/bin/menu-dns
wget -q -O /usr/bin/info "https://raw.githubusercontent.com/Tarap-Kuhing/tarong/main/tarong/MENU/info.sh" && chmod +x /usr/bin/info
wget -q -O /usr/bin/mspeed "https://raw.githubusercontent.com/Tarap-Kuhing/tarong/main/tarong/MENU/menu-speedtest.sh" && chmod +x /usr/bin/mspeed
wget -q -O /usr/bin/mbandwith "https://raw.githubusercontent.com/Tarap-Kuhing/tarong/main/tarong/MENU/menu-bandwith.sh" && chmod +x /usr/bin/mbandwith
wget -q -O /usr/bin/restart "https://raw.githubusercontent.com/Tarap-Kuhing/tarong/main/tarong/MENU/restart.sh" && chmod +x /usr/bin/restart
wget -q -O /usr/bin/menu-update "https://raw.githubusercontent.com/Tarap-Kuhing/tarong/main/tarong/MENU/menu-update.sh" && chmod +x /usr/bin/menu-update

chmod +x menu
chmod +x menu-ss
chmod +x menu-vmess
chmod +x menu-vless
chmod +x menu-trojan
chmod +x menu-bot
chmod +x menu-ssh
chmod +x menu-set
chmod +x menu-theme
chmod +x menu-backup
chmod +x menu-ip
chmod +x menu-tor
chmod +x menu-tcp
chmod +x autoboot
chmod +x menu-tcp
chmod +x rebootvps
chmod +x menu-dns
chmod +x info
chmod +x mspeed
chmod +x mbandwith
chmod +x restart
chmod +x menu-update
cd
